server:
  netty:
    connection-timeout: 60
  tomcat:
    connection-timeout: 60
    keep-alive-timeout: 60
  port: 9092
spring:
  profiles:
    active:
      - ${ENV:dev}
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 10s

logging:
  level:
    root: ${ROOT_LOG_LEVEL:info}
    web: ${WEB_LOG_LEVEL:info}
    com:
      elpsykongroo: ${APP_LOG_LEVEL:DEBUG}

management:
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${METRICS_TAG:kafka}
  endpoints:
    web:
      exposure:
        include: ${ENDPOINTS_WEB:prometheus}
service:
  vault:
    enable: ${VAULT_ENABLE:true}
  #    refreshDuration: ${VAULT_REFRESH_DURATION:30000}
  limit:
    bucket: ${BUCKET_LIMIT:true}
    ip:
      enable: ${IP_LIMIT:true}
      duration:
        refresh: ${IP_LIMIT_REFRESH:600000}
        white: ${IP_WHITE_CACHE_MIN:10}
        black: ${IP_BLACK_CACHE_MIN:30}
  record: ${SERVICE_RECORD:true}
  #  security: oauth2
