server:
  http2:
    enabled: true
#  netty:
#    connection-timeout: -1
  tomcat:
    connection-timeout: 12000
    keep-alive-timeout: 12000
    max-swallow-size: 10MB
    max-http-form-post-size: 10MB
  port: 9999
spring:
  servlet:
    multipart:
#      max-request-size: 10MB
      max-file-size: 10MB
      resolve-lazily: true
  lifecycle:
    timeout-per-shutdown-phase: 10s
#  security:
#    oauth2:
#      resourceserver:
#        opaque-token:
#          introspection-uri: ${AUTH_URL:http://localhost:9000}/oauth2/introspect
#          client-id: init
#          client_secret: just for init
service:
  vault:
    enable: ${VAULT_ENABLE:true}
  #    refreshDuration: ${VAULT_REFRESH_DURATION:30000}
  limit:
    bucket: ${BUCKET_LIMIT:true}
    ip:
      enable: ${IP_LIMIT:true}
      duration:
        refresh: ${IP_LIMIT_REFRESH:600000}
        white: ${IP_WHITE_CACHE_MIN:10}
        black: ${IP_BLACK_CACHE_MIN:30}
  record: ${SERVICE_RECORD:true}
#  security: oauth2
logging:
  level:
    root: ${ROOT_LOG_LEVEL:info}
    web: ${WEB_LOG_LEVEL:debug}
    org:
      springframework:
        security: ${SECURITY_LOG_LEVEL:debug}
    com:
      elpsykongroo: ${APP_LOG_LEVEL:debug}
management:
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-headers: "*"
        allowed-methods: OPTIONS, GET
      exposure:
        include: ${ENDPOINTS_WEB:health,prometheus}