server:
  port: 8379
logging:
  level:
    root: ${ROOT_LOG_LEVEL:info}
    web: ${WEB_LOG_LEVEL:debug}
    com:
      elpsykongroo: ${APP_LOG_LEVEL:debug}
#spring:
#  data:
#    redis:
#      cluster:
#        -  ${REDIS_NODES:redis-cluster.redis.svc:6379}
#      lettuce:
#        pool:
#          enabled: true
service:
  limit:
    bucket: false
    ip:
      enable: false
  vault:
    enable: ${VAULT_ENABLE:true}
    refreshDuration: ${VAULT_REFRESH_DURATION:30000}
