server:
  port: 8379
logging:
  level:
    root: ${ROOT_LOG_LEVEL:info}
    web: ${WEB_LOG_LEVEL:debug}
    com:
      elpsykongroo: ${APP_LOG_LEVEL:debug}
#spring:
#  data:
#    redis:
#      cluster:
#        -  ${REDIS_NODES:redis-cluster.redis.svc:6379}
#      lettuce:
#        pool:
#          enabled: true
service:
  vault:
    enable: ${VAULT_ENABLE:true}
  #    refreshDuration: ${VAULT_REFRESH_DURATION:30000}
  limit:
    bucket: ${BUCKET_LIMIT:true}
    ip:
      enable: ${IP_LIMIT:true}
      duration:
        refresh: ${IP_LIMIT_REFRESH:600000}
        white: ${IP_WHITE_CACHE_MIN:10}
        black: ${IP_BLACK_CACHE_MIN:30}
  record: ${SERVICE_RECORD:true}
#  security: oauth2
